config/routes.rb
Shop::Application.routes.draw do
  resources :mall
  resources :carts do
    put :delete_item, :on => :collection
  end
  resources :products
  match "/auth/:provider/callback" => "sessions#auth"
  resources :sessions do
    put :unauth, :on => :collection
    get :weibo, :on => :collection
  end
  resources :users

  root :to => 'mall#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    attr_accessible :user_id
	acts_as_shopping_cart_using :cart_item
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	acts_as_shopping_cart_item_for :cart
	attr_accessible :item, :price, :quantity
end

app/models/m_category.rb
#encoding:utf-8
class MCategory < ActiveRecord::Base
  attr_accessible :code, :name, :parent_id
  has_ancestry :cache_depth => true
  default_scope :order => "ancestry_depth ASC"

  scope :hidden, where(:is_hidden => true)
  scope :show, where(:is_hidden => false)

  def hidden
  	self.subtree.update_all(:is_hidden => true)
    Product.where(:m_category_id => self.subtree_ids).update_all(:is_selling => false)
  end

  def show
  	self.subtree.update_all(:is_hidden => false)
  end
end

app/models/open_api_user.rb
#encoding:utf-8
class OpenApiUser < ActiveRecord::Base
	belongs_to :user
end

app/models/product.rb
#encoding:utf-8
class Product < ActiveRecord::Base
  attr_accessible :barcode, :description, :is_selling, :m_category_id, :name, :remark, :price
  belongs_to :m_category
  has_many :supplier_wares
  has_many :suppliers, :through => :supplier_wares
  has_many :product_pictures                                   
  has_one :product_picture,:order => "position asc"             

  validates_numericality_of :price, :greater_than => 0
  validates_presence_of :name, :price, :m_category_id

  scope :selling, where(:is_selling => true)
  scope :un_selling, where(:is_selling => false)
  scope :is_un_selling, lambda{|arr| if arr.to_i==0; un_selling; elsif arr.to_i==1; selling; end; }

  def selling!
  	self.is_selling = true
  	self.save!
  end

  def un_sale!
  	self.is_selling = false
  	self.save!
  end
end

app/models/product_picture.rb
#encoding:utf-8
class ProductPicture < ActiveRecord::Base
	belongs_to :product

	has_attached_file :avatar,
    :styles => {:large => "400x400>",:medium => "160x160>", :thumb => "75x75>",:big => "1500x1500>"},
    :url  => "/system/product:base_url/:style/:filename",
    :default_style => :big
    process_in_background :avatar

    default_scope :order => "product_pictures.position , product_pictures.id"

end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base
	has_one :cart
	has_many :open_api_users
	has_one :weibo, :class_name => "OpenApiUser", :conditions => "open_api_users.open_api_type = 3"
end

app/controllers/application_controller.rb
#encoding:utf-8
class ApplicationController < ActionController::Base
  before_filter :get_parent_category
  helper_method :current_user, :current_cart

  def get_parent_category
  	@p_categories = MCategory.where(:ancestry_depth => 1)
  end

  def current_cart
	@current_cart = session[:cart_id] && Cart.find_by_id(session[:cart_id]) ? Cart.find(session[:cart_id]) : Cart.create
  	if current_user 
  		if current_user.cart && current_user.cart != @current_cart
  			current_user.cart.shopping_cart_items.each do |item|
   				@current_cart.add(item.item,item.price,item.quantity)
  			end
  			current_user.cart.destroy
  		end
  		@current_cart.user = current_user
  		@current_cart.save
  	end
  	session[:cart_id] = @current_cart.id
  	return @current_cart
  end

  def current_user
  	@current_user ||= User.find_by_id session[:user_id]
  end

end

app/controllers/carts_controller.rb
#encoding:utf-8
class CartsController < ApplicationController

  def index
    @current_cart = current_cart
    @shopping_cart_items = @current_cart.shopping_cart_items.includes(:item)
  end

  def create
    @product = Product.selling.find(params[:pid])
    current_cart.add(@product, @product.price,params[:pcount].to_i)
    redirect_to :back
  end

  def delete_item
  	@product = Product.find params[:pid]
  	current_cart.remove(@product, params[:pcount].to_i)
  	redirect_to :back
  end

end

app/controllers/mall_controller.rb
#encoding:utf-8
class MallController < ApplicationController
	def index
		if params[:p1] && params[:p2]
  		  @p_category = MCategory.find(params[:p1])
  		  @ch_category = MCategory.find params[:p2]
  		  @ch_categories = @p_category.children
		  @products = Product.selling.where(:m_category_id => @ch_category.subtree_ids)
		elsif params[:p1]
		  @p_category = MCategory.find(params[:p1])
		  @ch_categories = @p_category.children
  		  @products = Product.selling.where(:m_category_id => @p_category.subtree_ids)
		else
		  @ch_categories = MCategory.where(:ancestry_depth => 2)
		  @products = Product.selling.where(:m_category_id => MCategory.select('id').map(&:id))
		end
	end
end

app/controllers/products_controller.rb
#encoding:utf-8
class ProductsController < ApplicationController

	def show
		@product = Product.find params[:id]
	end

end

app/controllers/sessions_controller.rb
#encoding:utf-8
class SessionsController < ApplicationController

	def weibo
        session['omniauth.state'] = SecureRandom.hex(16)
        options = {
            client_id: 600434063,
            redirect_uri: "http://127.0.0.1:4000/auth/weibo/callback",
            state: session['omniauth.state']
        }
        authorize_url = "https://api.weibo.com/oauth2/authorize?#{options.map{|k, v|"#{CGI::escape(k.to_s)}=#{CGI::escape(v.to_s)}"}.join('&')}"

        redirect_to authorize_url if authorize_url
	end

	def auth
		omniauth = request.env['omniauth.auth']
		@weibo = OpenApiUser.where(:open_user_no => omniauth[:uid], :open_api_type => 3).first
		@user = @weibo.try(:user)
		if @user  #有用户，说明微博帐号已绑定客户帐号，直接登录
			session[:user_id] = @user.id
			redirect_to root_path
		elsif @weibo && !@user #有微博信息，无用户信息，第一次登录绑定已有帐号或注册新的帐号
			@user = User.new
		else #无微博信息和用户信息，先存微博记录，再绑定用户
			@weibo = OpenApiUser.new
			@weibo.open_user_no = omniauth[:uid]
			@weibo.open_api_type = 3
			@weibo.token = omniauth[:credentials][:token] 
			@weibo.save
			@user = User.new
		end
	end

	def unauth
		session[:user_id] = nil
    	#@weibo = OpenApiUser.where(:open_api_type => params[:type],:user_id => params[:user_id]).first
    	#@weibo.user_id = nil
    	#@weibo.save
    	flash[:notice] = "已接触绑定"
    	redirect_to root_path
	end
end

app/controllers/users_controller.rb
#encoding:utf-8
class UsersController < ApplicationController
	def create
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/mall_helper.rb
#encoding:utf-8
module MallHelper
	def cat_title(p_cat)
		r = ""
		r << "<em>#{p_cat.name}：</em>" if p_cat
		params[:p2].blank? ? r << "<strong>全部</strong>" : r << link_to( "全部", root_path(:p1 => params[:p1]))
		return raw(r)
	end

	def c_cat_title(c_cat)
		raw(params[:p2] == "#{c_cat.id}" ? "<strong>#{c_cat.name}</strong>" : link_to(c_cat.name, root_path(:p1 => c_cat.parent.id,:p2 => c_cat.id)))
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div class="all">
		<main class="fix">
			<ul class="cartNav fix">
				<li class="current">购物车</li>
				<li>支付</li>
				<li class="lastMargin">发货</li>
			</ul>
			<div class="cartDetail fix">
				<h4>您的购物车中的商品</h4>
				<ul>
					<% current_cart.shopping_cart_items.includes(:item).each do |cart_item| %>
					<li class="fix">
						<figure><%= link_to image_tag(cart_item.item.product_picture.avatar.url(:medium,false)), cart_item.item if cart_item.item.product_picture %></figure>
						<div>
							<h5><%= link_to '删除', delete_item_carts_path(pid: cart_item.item.id, pcount: cart_item.quantity), method: "put" %><%= cart_item.item.name %></h5>
							<p><span><em>单价：</em><%= cart_item.item.price %></span><span><em>数量：</em><input type="number" value="<%= cart_item.quantity %>"></span><span><em>合计：</em>¥ <%= cart_item.subtotal %></span><span><em>节省：</em>0</span></p>
						</div>
					</li>
					<% end %>
				</ul>
				<div class="total">
					<p>总计：<strong>¥ <%= current_cart.subtotal %></strong> 元，便宜 <strong>¥ 0</strong> 元</p>
					<p><button type="button">OK，下订单</button></p>
				</div>
			</div>
		</main>
	</div>

app/views/layouts/_shopping_cart.html.erb
            <div class="cartContent"><a href="">购物车：<strong><%= current_cart.total_unique_items %></strong>件，去结算&gt;</a></div>
				<div class="cartList">
					<ul>
					<% current_cart.shopping_cart_items.includes(:item).each do |cart_item| %>
						<li class="fix">
							<figure><%= link_to image_tag(cart_item.item.product_picture.avatar.url(:medium,false)), cart_item.item if cart_item.item.product_picture %></figure>
							<div class="info">
								<p><%= link_to cart_item.item.name, cart_item.item %></p>
								<p><strong><%= cart_item.item.price %></strong> x <%= cart_item.quantity %></p>
								<p><%= link_to '删除', delete_item_carts_path(pid: cart_item.item.id, pcount: cart_item.quantity), method: "put" %></p>
								<p><%= link_to '-1', delete_item_carts_path(pid: cart_item.item.id, pcount: 1), method: "put" %> <%= link_to '+1', carts_path(pid: cart_item.item.id, pcount: 1), method: "post" %></p>
							</div>
						</li>
					<% end %>
					</ul>
					<div class="summary">
						<p>共<strong><%= current_cart.total_unique_items %></strong>件商品</p>
						<p>金额总计：<strong><%= current_cart.subtotal %></strong></p>
						<%= link_to "去购物车结算", carts_path %>
					</div>
				</div>

app/views/layouts/_sina_share.html.erb
<script type="text/javascript" charset="utf-8">
(function(){
  var _w = 86 , _h = 16;
  var param = {
    url:location.href,
    type:'6',
    count:'', /**是否显示分享数，1显示(可选)*/
    appkey:'3666450312', /**您申请的应用appkey,显示分享来源(可选)*/
    title:'', /**分享的文字内容(可选，默认为所在页面的title)*/
    pic:'', /**分享图片的路径(可选)*/
    ralateUid:'', /**关联用户的UID，分享微博会@该用户(可选)*/
    language:'zh_cn', /**设置语言，zh_cn|zh_tw(可选)*/
    dpc:1
  }
  var temp = [];
  for( var p in param ){
    temp.push(p + '=' + encodeURIComponent( param[p] || '' ) )
  }
  document.write('<iframe allowTransparency="true" frameborder="0" scrolling="no" src="http://service.weibo.com/staticjs/weiboshare.html?' + temp.join('&') + '" width="'+ _w+'" height="'+_h+'"></iframe>')
})()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=7, IE=9, chrome=1">
	<meta http-equiv="x-dns-prefetch-control" content="on">
	<meta name="keywords" content="邮品,邮票,钱币,纸钞,金银币,邮币卡,收藏品,艺术品,投资,邮票价格行情,钱币价格行情,纸钞价格行情,艺术品网络拍卖,艺术品网拍,现场拍卖,在线拍卖">
	<meta name="description" content="中国首家同时拥有现场拍卖与在线拍卖的专业艺术品拍卖公司，是在线拍卖市场创新的领头羊。业务涵盖：邮票、钱币、纸钞、中国书画等。">
	<meta name="copyright" content="华宇拍卖">
	<title><%= yield(:title).blank? ? '华宇商城 -上海华宇拍卖有限公司' : yield(:title) %></title>
	<link href="http://www.huabid.com/" rel="dns-prefetch">
	<link href="http://www.google-analytics.com/" rel="dns-prefetch">
	<link href="/assets/favicon.ico" rel="shortcut icon">
	<%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
	<!--[if lt IE 9]>
	<script src="js/html5.js"></script>
	<![endif]-->
</head>

<!--=== *** 重要：未换行和换行的部分都请保持原状，否则会引起IE浏览器的布局差异！ *** ===-->
<body class="shop">
	<header>
		<div id="topNav">
			<div class="all fix">
				<div id="logo"><a href=""></a></div>
				<ul class="fix">
					<li><a href="">在线拍卖</a></li>
					<li><a href="">现场拍卖</a></li>
					<li class="current"><%= link_to "商城", root_path %></li>
					<li><a href="">求售</a></li>
					<li><a href="">社区</a></li>
				</ul>
				<div id="search"><input type="search" placeholder="输入拍品编号或名称"><button type="submit">搜索</button></div>
				<div class="link">
				<% if current_user.present? %>
					<%= session[:user_id] %> <%= current_user.try(:true_name) %> <%= link_to "退出", unauth_sessions_path(:type => 3, :user_id => current_user.id), :method => 'put' if current_user %>
				<% else %>
				    <a href="">登录</a>&middot;<a href="">注册</a>&middot;
				<% end %>
				<a href="">帮助</a></div>
			</div>
		</div>
		<nav>
			<div class="all fix">
				<div class="announcement">
					<a href="">首页公告位置首页公告位置</a>
				</div>
			</div>
		</nav>
	</header>
	  <%= yield %>
	<footer>
		<div class="all">
			<p class="link"><a href="">关于我们</a><a href="">业务团队</a><a href="">诚聘英才</a><a href="">联系我们</a><a href="">交通指南</a><a href="">帮助中心</a><a href="">友情链接</a></p>
			<p>400客户服务热线：<em>400-836-1788</em>　　Copyright &copy; HuaBid 2012 - 2013 • All rights reserved • 沪ICP备11050421</p>
			<p><a href="">华夏收藏</a><span>|</span><a href="">2345</a><span>|</span><a href="">易收藏</a><span>|</span><a href="">东方收藏</a><span>|</span><a href="">东方财富</a></p>
		</div>
	</footer>
	<script>
		$(function(){
			$(".shoppingCart").hover(function(){$(".cartList").show();}, function(){$(".cartList").hide();});
			$(window).scroll(function(){
				if($(this).scrollTop()>124){
					$(".shoppingCart").css({"position": "fixed", "top": "0"});
				}else{
					$(".shoppingCart").css({"position": "absolute", "top": "4px"});
				}
			});
		});
	</script>
</body>
</html>

app/views/mall/index.html.erb
	<div class="all">
		<div class="fr">
			<div class="shoppingCart">
				<%= render "layouts/shopping_cart" %>
			</div>
		</div>
		<main class="fix">
			<h3>华宇·集藏用品专门店</h3>
			<ul class="category fix">
				<% @p_categories.each do |p_cat| %>
				  <li><a href="<%= root_path(:p1 => p_cat.id)%>" class='<%= params[:p1] == "#{p_cat.id}" ? "current" : nil %>' ><dl><dt><%= image_tag p_cat.name.include?('集邮') ? "temp/stamp.png" : "temp/coin.png" %></dt><dd><%= p_cat.name %></dd></dl></a></li>
				<% end %>
			</ul>
			<div class="goodsList">
				<h4 class="child_category" style="display:block">
					<%= cat_title(@p_category) %>
					<% @ch_categories.each do |c_cat| %>
					    <%= c_cat_title(c_cat) %>
					<% end %>
				</h4>
				<ul class="fix">
					
					<% @products.each_with_index do |product,index| %>
					<% index += 1%>
					<li class='<%= index%3 == 0 ? "last" : nil %>'>
						<dl>
							<dt><%= link_to image_tag(product.product_picture.avatar.url(:medium,false)), product, :class => "dddd" if product.product_picture %></dt>
							<dd>
								<p><%= link_to truncate(product.name, length: 20), product, title: product.name %></p>
								<p><strong><%= product.price %></strong></p>
								<p class="tac"><%= link_to '<button class="addToShop" type="button">立即购买</button>'.html_safe, carts_path(pid: product.id, pcount: 1), method: "post", :class => "addButton" %></p>
							</dd>
						</dl>
					</li>
					<% end %>
				</ul>
			</div>
		</main>
	</div>

app/views/products/show.html.erb
	<div class="all">
		<div class="fr">
			<div class="shoppingCart">
				<%= render "layouts/shopping_cart" %>
			</div>
		</div>
		<main class="fix">
			<h3>华宇·集藏用品专门店</h3>
			<ul class="category fix">
				<% @p_categories.each do |p_cat| %>
				  <li><a href="<%= root_path(:p1 => p_cat.id)%>" class='<%= params[:p1] == "#{p_cat.id}" ? "current" : nil %>' ><dl><dt><%= image_tag p_cat.name.include?('集邮') ? "temp/stamp.png" : "temp/coin.png" %></dt><dd><%= p_cat.name %></dd></dl></a></li>
				<% end %>
			</ul>
			<script type="text/javascript">
			$(function(){
				$('.zoom_image').zoom({
					url: $('.zoom_image').find('img:first').attr('src').replace('large','big')
				});
				$('.picList').on('mouseover','li',function(){
					$(".selected").attr('class', 'noneSelect');
					$(this).attr('class','selected');
					$('.zoom_image').find('img:first').attr({src: $(this).find('img:first').attr('src').replace('thumb','large')});
					$('.zoom_image').find('img:last').attr({src: $(this).find('img:first').attr('src').replace('thumb','big')});
				});
			});
			</script>
			<div class="goodsDetail fix">
				<div class="goodsPic">
					<table><tr><td><span class="zoom_image"><%= image_tag('rails.png') %></span></td></tr></table>
					<ul class="picList fix">
						<% @product.product_pictures.each_with_index do |pp,index| %>
						  <li class='<%= index == 0 ? "selected" : "noneSelect" %>'><%= link_to image_tag(pp.avatar.url(:thumb,false)), pp.avatar.url, :target => "blank", :title => "点击查看详细大图" %></li>
						<% end %>
					</ul>
				</div>
				<div class="goodsInfo">
					<h4><%= @product.name %></h4>
					<p class="f14 red"><%= @product.price %><%= link_to '<button class="addToShop" type="button">添加到购物车</button>'.html_safe, carts_path(pid: @product.id, pcount: 1), method: "post", :class => "addButton" %></p>
					<p><a href="">率先评论此产品</a></p>
					<p>预计发货时间：24 小时内</p>
					<p><%= render "layouts/sina_share" %></p>
					<p><%= link_to "解除微博绑定", unauth_sessions_path(:type => 3, :user_id => current_user.id), :method => 'put' if current_user && current_user.weibo %></p>
					<p><%= link_to "微博登录", weibo_sessions_path, :method => 'get' unless current_user %></p>
				</div>
			</div>
			<div class="goodsAttached fix">
				<div class="attachMenu"><a href="">产品信息</a><a href="">评级与评论<em>（10）</em></a><a class="lastBorder" href="">问答<em>（10）</em></a></div>
				<h5>产品信息</h5>
				<dl class="fix">
					<dt>概述</dt>
					<dd><%= @product.description %></dd>
				</dl>
				<dl class="fix">
					<dt>亮点</dt>
					<dd><%= raw @product.advantage %></dd>
				</dl>
				<div class="shadow"></div>
				<h5>评级与评论</h5>
				<dl class="fix">
					<dt><a href="">率先评论此产品</a></dt>
				</dl>
			</div>
			<div class="goodsList">
				<h4 class="tac"><em>客户还购买了</em></h4>
				<ul class="fix">
					<li>
						<dl>
							<dt><a href=""><%= image_tag "temp/bid_item.jpg" %></a></dt>
							<dd>
								<p><a href="">这里是商品名称这里是商品名称这里是商品名称这里是商品名称</a></p>
								<p><strong>¥ 1,900,2900.00</strong></p>
								<p class="tac"><button type="button">立即购买</button></p>
							</dd>
						</dl>
					</li>
					<li>
						<dl>
							<dt><a href=""><%= image_tag "temp/bid_item.jpg" %></a></dt>
							<dd>
								<p><a href="">这里是商品名称这里是商品名称这里是商品名称这里是商品名称</a></p>
								<p><strong>¥ 1,900,2900.00</strong></p>
								<p class="tac"><button type="button">立即购买</button></p>
							</dd>
						</dl>
					</li>
					<li class="last">
						<dl>
							<dt><a href=""><%= image_tag "temp/bid_item.jpg" %></a></dt>
							<dd>
								<p><a href="">这里是商品名称这里是商品名称这里是商品名称这里是商品名称</a></p>
								<p><strong>¥ 1,900,2900.00</strong></p>
								<p class="tac"><button type="button">立即购买</button></p>
							</dd>
						</dl>
					</li>
				</ul>
			</div>
		</main>
	</div>
		</main>
	</div>